services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/submissions:/app/submissions
      - ./backend/logs:/app/logs
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

volumes:
  submissions:
  logs:
